# write a map of security key messages to fixed versions
# for example
# 'rails_commit_343434334' : '3.2.6'
# use '0.0.0' as a version to ignore the security message
'rails_commit_34344334' : '3.2.6'
'rails_commit_12344' : '0.0.0'

