require "gems-status/checkers/exists_in_upstream"
require "gems-status/checkers/git_check_messages"
require "gems-status/checkers/hg_check_messages"
require "gems-status/checkers/not_a_security_alert_checker"
require "gems-status/checkers/not_native_gem_checker"
require "gems-status/checkers/not_rails_checker"
require "gems-status/checkers/scm_check_messages"
require "gems-status/checkers/scm_security_messages"
require "gems-status/checkers/svn_check_messages"
require "gems-status/checkers/print_gem_versions"

